[package]
name = "aztec_gateway_7683"
type = "contract"
authors = ["Substance Labs"]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.2", directory = "noir-projects/aztec-nr/aztec" }
token = { git = "https://github.com/defi-wonderland/aztec-standards.git", tag = "v3.0.0-devnet.2", directory = "src/token_contract" }
